# Generated by Django 3.0.5 on 2020-04-23 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogect',
            new_name='Blogs',
        ),
    ]
